In [1]:
import numpy as np

In [2]:
#creating a one dimensional array
array = np.array(range(5))

In [3]:
array

array([0, 1, 2, 3, 4])

In [4]:
#creating a two dimensional array
array_2d = np.array([range(5), range(5)])

In [5]:
array_2d 

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [6]:
array.shape

(5,)

In [7]:
array_2d.shape

(2, 5)

In [9]:
array.ndim

1

In [10]:
array_2d.ndim

2

In [11]:
num_array = np.array([range(5), range(5)])
num_array

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [36]:
num_array2 = np.arange(5)
num_array2 

array([0, 1, 2, 3, 4])

In [37]:
#Random number generator
rng = np.random.default_rng(616)

rng.random(10)

array([0.39682145, 0.86568572, 0.46040359, 0.30599848, 0.57381588,
       0.08888468, 0.88194347, 0.73228387, 0.73215182, 0.56233394])

In [38]:
rng.integers(0,10,100)

array([8, 3, 6, 0, 3, 3, 1, 2, 2, 4, 9, 1, 2, 5, 1, 8, 9, 0, 3, 1, 5, 8,
       0, 6, 1, 7, 0, 7, 6, 0, 3, 7, 1, 9, 4, 1, 6, 1, 4, 4, 9, 5, 3, 4,
       7, 8, 3, 3, 5, 0, 4, 9, 9, 5, 6, 5, 8, 2, 3, 0, 0, 8, 3, 8, 4, 8,
       8, 9, 7, 3, 8, 4, 9, 2, 6, 3, 0, 3, 2, 0, 0, 4, 9, 5, 4, 1, 8, 2,
       7, 7, 1, 2, 2, 4, 1, 6, 7, 3, 7, 5], dtype=int64)

In [41]:
rng.normal(50,5,10)

array([53.53115044, 46.35468178, 46.1580894 , 52.89177118, 45.90693639,
       44.51748741, 57.41467712, 51.82624671, 53.9032125 , 53.21454641])

In [42]:
product = ("fruits","vegetables","cereal","dairy","eggs","snacks","beverages","coffee","tea","spices")

product_array = np.array(product)

product_array

array(['fruits', 'vegetables', 'cereal', 'dairy', 'eggs', 'snacks',
       'beverages', 'coffee', 'tea', 'spices'], dtype='<U10')

In [43]:
product_array[1]

'vegetables'

In [44]:
product_array[:5]

array(['fruits', 'vegetables', 'cereal', 'dairy', 'eggs'], dtype='<U10')

In [45]:
product_array[5::2]

array(['snacks', 'coffee', 'spices'], dtype='<U10')

In [46]:
product_array2 = product_array.reshape(2,5)
product_array2

array([['fruits', 'vegetables', 'cereal', 'dairy', 'eggs'],
       ['snacks', 'beverages', 'coffee', 'tea', 'spices']], dtype='<U10')

In [47]:
#goes to second row, third element
product_array2[1,2]

'coffee'

In [ ]:
#all row, grabs elements starting at 3rd
product_array2[:,2:]

In [48]:
#goes to second row and grabs all elements
product_array2[1:,:]

array([['snacks', 'beverages', 'coffee', 'tea', 'spices']], dtype='<U10')